out_dir: results
metric_best: mae 
metric_agg: argmin 
wandb:
  use: False
dataset:
  format: Custom  
  name: customDataset
  task: node
  task_type: regression
  transductive: False  
  node_encoder: False
  edge_encoder: True
  edge_encoder_name: DummyEdge
  edge_encoder_bn: False
  split: [0.8, 0.1, 0.1]
  split_mode: standard
pretrained:
  dir: pretrained/custom_simple_gatedgcn_regression
  reset_prediction_head: False
train:
  pkl_filepath:  "test_data.pkl" 
  mode: inference-only #
  batch_size: 1
  eval_period: 1
  ckpt_period: 10
model:
  emb_dim_category: 3  # embedding dimension for 'category'
  emb_dim_operator_class: 3  # embedding dimension for 'category'
  num_operator_classes: 62
  num_categories: 32
  type: custom_gnn
  loss_fun: l1  
gnn:
  head: inductive_node
  layers_pre_mp: 1
  layers_mp: 5
  layers_post_mp: 2
  dim_inner: 40
  layer_type: gatedgcnconv
  act: relu
  residual: True
  dropout: 0.1
  agg: sum
  normalize_adj: False
optim:
  optimizer: adam
  weight_decay: 1e-6
  base_lr: 0.01
  scheduler: reduce_on_plateau
  reduce_factor: 0.5
  schedule_patience: 2
  min_lr: 1e-5
  max_epoch: 50

